// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cards/flow.proto

// Protobuf Java Version: 3.25.3
package com.wecasino.proto.cards;

public final class FlowProto {
  private FlowProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020cards/flow.proto\022\005cards*K\n\010FlowCard\022\031\n" +
      "\025FLOW_CARD_UNSPECIFIED\020\000\022\021\n\rFLOW_NEW_SHO" +
      "E\020\001\022\021\n\rFLOW_SHOE_CUT\020\002BY\n\030com.wecasino.p" +
      "roto.cardsB\tFlowProtoP\001\242\002\003CXX\252\002\005Cards\312\002\005" +
      "Cards\342\002\021Cards\\GPBMetadata\352\002\005Cardsb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
